//
//  MoreDeviceCapability.swift
//  
//
//  Created by p-x9 on 2023/08/27.
//  
//

import Foundation

extension MobileGestaltKey {
    // More Device Capabilities
    public enum MoreDeviceCapability: String, CaseIterable, MobileGestaltKeyProtocol {
        case deviceSupportsLiquidDetection_CorrosionMitigation = "DeviceSupportsLiquidDetection_CorrosionMitigation"
        case deviceSupportsAdvancedVoiceProcessorChatFlavor = "DeviceSupportsAdvancedVoiceProcessorChatFlavor"
        case deviceSupportsFrameSynchronousBrightness = "DeviceSupportsFrameSynchronousBrightness"
        case deviceSupportsUnconditionalPluckItCollection = "DeviceSupportsUnconditionalPluckItCollection"
        case deviceSupportsEnvironmentalDosimetry = "DeviceSupportsEnvironmentalDosimetry"
        case deviceSupportsOnDemandPhotoAnalysis = "DeviceSupportsOnDemandPhotoAnalysis"
        case deviceSupportsDoNotDisturbWhileDriving = "DeviceSupportsDoNotDisturbWhileDriving"
        case deviceSupportsPortraitLightEffectFilters = "DeviceSupportsPortraitLightEffectFilters"
        case deviceSupportsStudioLightPortraitPreview = "DeviceSupportsStudioLightPortraitPreview"
        case deviceSupportsStageLightPortraitPreview = "DeviceSupportsStageLightPortraitPreview"
        case deviceSupportsPortraitIntensityAdjustments = "DeviceSupportsPortraitIntensityAdjustments"
        case deviceSupportsBatteryModuleAuthentication = "DeviceSupportsBatteryModuleAuthentication"
        case deviceSupportsWalkingRadiusAnimation = "DeviceSupportsWalkingRadiusAnimation"
        case deviceSupportsGrey = "DeviceSupportsGrey"
        case deviceSupports4G = "DeviceSupports4G"
        case deviceSupports4k = "DeviceSupports4k"
        case deviceSupportsBrook = "DeviceSupportsBrook"
        case deviceSupportsBeacon = "DeviceSupportsBeacon"
        case deviceSupportsNewton = "DeviceSupportsNewton"
        case deviceSupportsTethering = "DeviceSupportsTethering"
        case deviceSupportsToneMapping = "DeviceSupportsToneMapping"
        case deviceSupportsAdvancedMapRendering = "DeviceSupportsAdvancedMapRendering"
        case deviceSupportsLiveVideoRendering = "DeviceSupportsLiveVideoRendering"
        case deviceSupportsDClr = "DeviceSupportsDClr"
        case deviceSupportsDCP = "DeviceSupportsDCP"
        case deviceSupportsSiDP = "DeviceSupportsSiDP"
        case deviceSupportsConcurrentHPLPMics = "DeviceSupportsConcurrentHPLPMics"
        case deviceSupportsCameraCaptureOnTouchDown = "DeviceSupportsCameraCaptureOnTouchDown"
        case deviceSupportsSpatialOverCapture = "DeviceSupportsSpatialOverCapture"
        case deviceSupportsMomentCapture = "DeviceSupportsMomentCapture"
        case deviceSupportsMapsBlurredUI = "DeviceSupportsMapsBlurredUI"
        case deviceSupportsAdaptiveMapsUI = "DeviceSupportsAdaptiveMapsUI"
        case deviceSupportsPeriodicALSUpdates = "DeviceSupportsPeriodicALSUpdates"
        case deviceSupportsSideButtonClickSpeed = "DeviceSupportsSideButtonClickSpeed"
        case deviceSupportsSecureDoubleClick = "DeviceSupportsSecureDoubleClick"
        case deviceSupportsSecureMicrophone = "DeviceSupportsSecureMicrophone"
        case deviceSupportsFloorCounting = "DeviceSupportsFloorCounting"
        case deviceSupportsAbsoluteDepth = "DeviceSupportsAbsoluteDepth"
        case deviceSupportsCollisionSOS = "DeviceSupportsCollisionSOS"
        case deviceSupportsVSHCompensation = "DeviceSupportsVSHCompensation"
        case deviceSupportsCompassOrienteering = "DeviceSupportsCompassOrienteering"
        case deviceSupportsAlwaysOnCompass = "DeviceSupportsAlwaysOnCompass"
        case deviceSupportsAlwaysOnTime = "DeviceSupportsAlwaysOnTime"
        case deviceSupportsAlwaysListening = "DeviceSupportsAlwaysListening"
        case deviceSupportsWirelessSplitting = "DeviceSupportsWirelessSplitting"
        case deviceSupportsHiResBuildings = "DeviceSupportsHiResBuildings"
        case deviceSupportsActiveNFCReadingOnly = "DeviceSupportsActiveNFCReadingOnly"
        case deviceSupportsInductiveCharging = "DeviceSupportsInductiveCharging"
        case deviceSupportsCorrectedTemperature = "DeviceSupportsCorrectedTemperature"
        case deviceSupportsAbsoluteAltimeter = "DeviceSupportsAbsoluteAltimeter"
        case deviceSupportsDynamicEndOfCharge = "DeviceSupportsDynamicEndOfCharge"
        case deviceSupportsMapsOpticalHeading = "DeviceSupportsMapsOpticalHeading"
        case deviceSupportsFairPlaySecureVideoPath = "DeviceSupportsFairPlaySecureVideoPath"
        case deviceSupportsP3ColorspaceVideoRecording = "DeviceSupportsP3ColorspaceVideoRecording"
        case deviceSupportsStereoAudioRecording = "DeviceSupportsStereoAudioRecording"
        case deviceSupportsCameraDeferredProcessing = "DeviceSupportsCameraDeferredProcessing"
        case deviceSupportsHDRDeferredProcessing = "DeviceSupportsHDRDeferredProcessing"
        case deviceSupportsVoiceOverCanUseSiriVoice = "DeviceSupportsVoiceOverCanUseSiriVoice"
        case deviceSupportsLandscapeFaceID = "DeviceSupportsLandscapeFaceID"
        case deviceSupportsHardwareDetents = "DeviceSupportsHardwareDetents"
        case deviceSupportsApplePencil = "DeviceSupportsApplePencil"
        case deviceSupportsAppleLPM = "DeviceSupportsAppleLPM"
        case deviceSupportsSimplisticRoadMesh = "DeviceSupportsSimplisticRoadMesh"
        case deviceSupportsHeartHealthAlerts = "DeviceSupportsHeartHealthAlerts"
        case deviceSupportsSiriUnderstandingOnDevice = "DeviceSupportsSiriUnderstandingOnDevice"
        case deviceSupportsSingleDisplayEnhancedMultitasking = "DeviceSupportsSingleDisplayEnhancedMultitasking"
        case deviceSupportsEnhancedMultitasking = "DeviceSupportsEnhancedMultitasking"
        case deviceSupportsEnhancedAC3 = "DeviceSupportsEnhancedAC3"
        case deviceSupportsScandium = "DeviceSupportsScandium"
        case deviceSupportsTimeInDaylight = "DeviceSupportsTimeInDaylight"
        case deviceSupportsTelephonyOverUSB = "DeviceSupportsTelephonyOverUSB"
        case deviceSupportsExternalHDR = "DeviceSupportsExternalHDR"
        case deviceSupportsHeartRateVariability = "DeviceSupportsHeartRateVariability"
        case deviceSupportsDynamicEndOfChargeLegacyHW = "DeviceSupportsDynamicEndOfChargeLegacyHW"
        case deviceSupports3DImagery = "DeviceSupports3DImagery"
        case deviceSupportsAOP = "DeviceSupportsAOP"
        case deviceSupportsRGB10 = "DeviceSupportsRGB10"
        case deviceSupportsLockdown = "DeviceSupportsLockdown"
        case deviceSupportsLowLatency = "DeviceSupportsLowLatency"
        case deviceSupportsClosedLoopHaptics = "DeviceSupportsClosedLoopHaptics"
        case deviceSupportsCameraHaptics = "DeviceSupportsCameraHaptics"
        case deviceSupportsHaptics = "DeviceSupportsHaptics"
        case deviceSupportsAvatars = "DeviceSupportsAvatars"
        case deviceSupportsLaguna = "DeviceSupportsLaguna"
        case deviceSupportsELabel = "DeviceSupportsELabel"
        case deviceSupportsCarPlay2 = "DeviceSupportsCarPlay2"
        case deviceSupportsYCbCr10 = "DeviceSupportsYCbCr10"
        case deviceSupports1080p = "DeviceSupports1080p"
        case deviceSupportsLivePhotoAuto = "DeviceSupportsLivePhotoAuto"
        case deviceSupports720p = "DeviceSupports720p"
        case deviceSupportsNFC = "DeviceSupportsNFC"
        case deviceSupportsCCK = "DeviceSupportsCCK"
        case deviceSupportseARC = "DeviceSupportseARC"
        case deviceSupportsASTC = "DeviceSupportsASTC"
        case deviceSupportsAlmond = "DeviceSupportsAlmond"
        case deviceSupportsCinnamon = "DeviceSupportsCinnamon"
        case deviceSupportsLineIn = "DeviceSupportsLineIn"
        case deviceSupports9Pin = "DeviceSupports9Pin"
        case deviceSupportsMTP = "DeviceSupportsMTP"
        case deviceSupportsLongFormAudio = "DeviceSupportsLongFormAudio"
        case deviceSupportsPhotosLocalLight = "DeviceSupportsPhotosLocalLight"
        case deviceSupports3DMaps = "DeviceSupports3DMaps"
        case deviceSupportsSwimmingWorkouts = "DeviceSupportsSwimmingWorkouts"
        case deviceSupportsMultiUser = "DeviceSupportsMultiUser"
        case deviceSupportsBootChime = "DeviceSupportsBootChime"
        case deviceSupportsReverseZoom = "DeviceSupportsReverseZoom"
        case deviceSupportsRaiseToSpeak = "DeviceSupportsRaiseToSpeak"
        case deviceSupportsTapToWake = "DeviceSupportsTapToWake"
        case deviceSupportsUSBTypeC = "DeviceSupportsUSBTypeC"
        case deviceSupportsUSBTypeCDisplay = "DeviceSupportsUSBTypeCDisplay"
        case deviceSupportsHDRPhotoDisplay = "DeviceSupportsHDRPhotoDisplay"
        case deviceSupportsDisplayPort = "DeviceSupportsDisplayPort"
        case deviceSupportsSingleCameraPortrait = "DeviceSupportsSingleCameraPortrait"
        case deviceSupportsSWProRes = "DeviceSupportsSWProRes"
        case deviceSupportsAutoLowLightVideo = "DeviceSupportsAutoLowLightVideo"
        case deviceSupportsSiriBargeIn = "DeviceSupportsSiriBargeIn"
        case deviceSupportsSiriSpokenMessages = "DeviceSupportsSiriSpokenMessages"
        case deviceSupportsSiriSpeaks = "DeviceSupportsSiriSpeaks"
        case deviceSupportsSiriHub = "DeviceSupportsSiriHub"
        case deviceSupportsBerkelium2 = "DeviceSupportsBerkelium2"
        case deviceSupportsWebkit = "DeviceSupportsWebkit"
        case deviceSupportsThunderbolt = "DeviceSupportsThunderbolt"
        case deviceSupportsCrudeProx = "DeviceSupportsCrudeProx"
        case deviceSupportsCarIntegration = "DeviceSupportsCarIntegration"
        case deviceSupportsNavigation = "DeviceSupportsNavigation"
        case deviceSupportsCyclingAutoStartReminders = "DeviceSupportsCyclingAutoStartReminders"
        case deviceSupportsSpatialFaceTimeAudioPlayback = "DeviceSupportsSpatialFaceTimeAudioPlayback"
        case deviceSupportsTwilight = "DeviceSupportsTwilight"
        case deviceSupports80ChargeLimit = "DeviceSupports80ChargeLimit"
        case deviceSupportsIndependentOutputOnSpeaker = "DeviceSupportsIndependentOutputOnSpeaker"
        case deviceSupportsEUCapabilities = "DeviceSupportsEUCapabilities"
        case deviceSupportsWirelessChargingEnergyUseNotification = "DeviceSupportsWirelessChargingEnergyUseNotification"
        case deviceSupportsBatteryInformation = "DeviceSupportsBatteryInformation"
        case deviceSupportsElton = "DeviceSupportsElton"
        case deviceSupportsDynamicIsland = "DeviceSupportsDynamicIsland"

        case deviceSuportsExternalDriverKit = "DeviceSuportsExternalDriverKit"

        case supportsSSHBButtonType = "SupportsSSHBButtonType"
        case supportsBurninMitigation = "SupportsBurninMitigation"
        case supportsLowPowerMode = "SupportsLowPowerMode"
        case supportsPerseus = "SupportsPerseus"
        case supportedKeyboards = "SupportedKeyboards"
        case supportsLEDAging = "SupportsLEDAging"
        case supportsEDUMU = "SupportsEDUMU"
        case supportsSOS = "SupportsSOS"
        case supportsForceTouch = "SupportsForceTouch"
        case supportsTouchRemote = "SupportsTouchRemote"
        case supportsIrisCapture = "SupportsIrisCapture"
        case supportsRotateToWake = "SupportsRotateToWake"
        case supportsAlwaysListening = "supports-always-listening"

        case nikeSupport = "nike-support"
        case sikaSupport = "sika-support"
        case sandmanSupport = "sandman-support"
        case faceDetectionSupport = "face-detection-support"

        case lowPowerExpressModesSupported = "LowPowerExpressModesSupported"
        case blueLightReductionSupported = "BlueLightReductionSupported"
        case image4Supported = "Image4Supported"
        case _image4Supported = "image4-supported"

        case iap2ProtocolSupported = "iap2-protocol-supported"

        case highestSupportedVideoMode = "HighestSupportedVideoMode"
        
        case hardwareSupportsSecureDoubleClick = "HardwareSupportsSecureDoubleClick"

        case doesNotSupportGamekit = "does-not-support-gamekit"
    }
}
