//
//  Other.swift
//  
//
//  Created by p-x9 on 2023/10/23.
//  
//

import Foundation

extension MobileGestaltKey {
    public enum Other: String, CaseIterable, MobileGestaltKeyProtocol {
        case AVDDecodingRate = "AVDDecodingRate"
        case explicitContentRestriction = "explicitContentRestriction"
        case airDropRestriction = "airDropRestriction"
        case lowPowerWalletMode = "LowPowerWalletMode"

        case restrictedCountryCodes = "RestrictedCountryCodes"
        case certificateSecurityMode = "CertificateSecurityMode"
        case certificateProductionStatus = "CertificateProductionStatus"
        case allFeatures = "all-features"
        case callForwarding = "call-forwarding"
        case callWaiting = "call-waiting"
        case callerId = "caller-id"

        case multiLynxPublicKeyArray = "MultiLynxPublicKeyArray"
        case _3Gvenice = "3Gvenice"
        case venice = "venice"
        case lynxPublicKey = "LynxPublicKey"
        case multitasking = "multitasking"
        case multitaskingGestures = "multitasking-gestures"
        case siriGesture = "siri-gesture"
        case _720p = "720p"
        case RFExposureSeparationDistance = "RFExposureSeparationDistance"
        case FMFAllowed = "FMFAllowed"
        case countryOfOrigin = "CountryOfOrigin"
        case configNumber = "ConfigNumber"
        case isPwrOpposedVol = "IsPwrOpposedVol"
        case SDIOProductInfo = "SDIOProductInfo"
        case stockholmJcopInfo = "StockholmJcopInfo"
        case mixAndMatchPrevention = "MixAndMatchPrevention"
        case tvOutCrossfade = "tv-out-crossfade"
        case ioSurfaceBackedImages = "io-surface-backed-images"
        case cellBroadcast = "cell-broadcast"
        case ptpLargeFiles = "ptp-large-files"
        case hideNonDefaultApps = "hide-non-default-apps"
        case standAloneContacts = "stand-alone-contacts"
        case tvOutSettings = "tv-out-settings"
        case navajoFusingState = "NavajoFusingState"
        case assistant = "assistant"
        case tristarID = "TristarID"
        case systemImageID = "SystemImageID"
        case secureElementID = "SecureElementID"
        case secureElement = "SecureElement"
        case securityDomain = "SecurityDomain"
        case artworkTraits = "ArtworkTraits"
        case artworkTraitDisplayGamut = "ArtworkTraitDisplayGamut"
        case UIReachability = "UIReachability"
        case accessibility = "accessibility"
        case sensitiveUi = "sensitive-ui"
        case SBAllowSensitiveUI = "SBAllowSensitiveUI"
        case acousticID = "AcousticID"
        case WAGraphicQuality = "WAGraphicQuality"
        case tvosPerfLevel1 = "tvos-perf-level-1"
        case iosPerfLevel2 = "ios-perf-level-2"
        case hiccoughInterval = "hiccough-interval"
        case voiceControl = "voice-control"
        case hapticsPowerControlFeatures = "HapticsPowerControlFeatures"
        case UIBackgroundQuality = "UIBackgroundQuality"
        case appCapacityTVOS = "AppCapacityTVOS"
        case iceFallID = "IceFallID"
        case icefallInfo = "IcefallInfo"
        case monarchLowEndHardware = "MonarchLowEndHardware"
        case gasGaugeBattery = "gas-gauge-battery"
        case shouldHactivate = "ShouldHactivate"
        case groundhogEnabled = "GroundhogEnabled"
        case role = "role"
        case requiresPairedRemote = "RequiresPairedRemote"
        case requiresNaturalVolumeButtonArrangement = "RequiresNaturalVolumeButtonArrangement"
        case SBCanForceDebuggingInfo = "SBCanForceDebuggingInfo"
        case N78aHack = "N78aHack"
        case WSKU = "WSKU"
        case buddyLanguagesAnimationRequiresOptimization = "BuddyLanguagesAnimationRequiresOptimization"
        case encryptedDataPartition = "encrypted-data-partition"
        case fccLogosViaSoftware = "fcc-logos-via-software"
        case loadThumbnailsWhileScrolling = "load-thumbnails-while-scrolling"
        case AWDID = "AWDID"
        case NFCRadio = "NFCRadio"
        case WLANBkgScanCache = "WLANBkgScanCache"

        case rendersLetterPressSlowly = "RendersLetterPressSlowly"
        case activeWirelessTechnology = "ActiveWirelessTechnology"
        case inDiagnosticsMode = "InDiagnosticsMode"
        case videoStills = "video-stills"
        case delaySleepForHeadsetClick = "delay-sleep-for-headset-click"
        case enforceShutterClick = "enforce-shutter-click"
        case reverseZoom = "reverse-zoom"
        case apNonceRetrieve = "ApNonceRetrieve"
        case actuatorResonantFrequency = "ActuatorResonantFrequency"
        case renderWideGamutImagesAtDisplayTime = "RenderWideGamutImagesAtDisplayTime"
        case macPrefsAssetImage = "MacPrefsAssetImage"
        case image4CryptoHashMethod = "Image4CryptoHashMethod"
        case skey = "Skey"
        case sysCfg = "SysCfg"
        case sysCfgDict = "SysCfgDict"
        case diagData = "DiagData"
        case peekUIWidth = "PeekUIWidth"
        case SDIOManufacturerTuple = "SDIOManufacturerTuple"
        case icefallInRestrictedMode = "IcefallInRestrictedMode"
        case researchFuse = "ResearchFuse"
        case ephemeralDataModeOverride = "EphemeralDataModeOverride"
        case ephemeralDataModeEnabled = "EphemeralDataModeEnabled"
        case isLargeFormatPhone = "IsLargeFormatPhone"
        case macFormFactor = "MacFormFactor"
        case IOSurfaceFormatDictionary = "IOSurfaceFormatDictionary"
        case name = "name"
        case macBridgingKeys = "MacBridgingKeys"
        case signingFuse = "SigningFuse"
        case compassType = "CompassType"
        case releaseType = "ReleaseType"
        case isServicePart = "IsServicePart"
        case mms = "mms"
        case workoutUltraMode = "WorkoutUltraMode"
        case airplaneMode = "AirplaneMode"
        case sms = "sms"
        case applicationInstallation = "applicationInstallation"
        case additionalTextTones = "additional-text-tones"
        case DMin = "DMin"
        case recoveryOSVersion = "RecoveryOSVersion"
        case dieId = "DieId"
        case die_Id = "die-id"
        case bridgeRestoreVersion = "BridgeRestoreVersion"
        case rotateToWakeStatus = "RotateToWakeStatus"
        case SEInfo = "SEInfo"
        case savageInfo = "SavageInfo"
        case FDRSealingStatus = "FDRSealingStatus"
        case dictation = "dictation"
        case tribecaSettings = "TribecaSettings"
        case EOSHalleyConfiguration = "EOSHalleyConfiguration"
        case VSHCompensationMinimumNits = "VSHCompensationMinimumNits"
        case compatibleAppVariants = "CompatibleAppVariants"
        case kConferenceCallType = "kConferenceCallType"
    }
}
